In [1]:
import pandas as pd
import numpy as np
import time
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [4]:
df = pd.read_csv("Bank Customer Churn Prediction.csv")

In [5]:
df

,customer_id,credit_score,country,gender,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
0,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,15606229,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,15569892,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,15584532,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,15682355,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,15628319,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [6]:
df.describe()

,customer_id,credit_score,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
count,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [7]:
df.shape

(10000, 12)

In [8]:
df.isnull().sum()

customer_id         0
credit_score        0
country             0
gender              0
age                 0
tenure              0
balance             0
products_number     0
credit_card         0
active_member       0
estimated_salary    0
churn               0
dtype: int64

In [9]:
df = df.drop("customer_id", axis=1)

In [11]:
categorical_cols = ["country", "gender"]

for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

In [13]:
X = df.drop("churn", axis=1)
y = df["churn"]

In [14]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [16]:
model = RandomForestClassifier(n_estimators=150, random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=150, random_state=42)

In [17]:
y_pred = model.predict(X_test)

print("\nAccuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report\n")
print(classification_report(y_test, y_pred))

Accuracy: 0.864

Classification Report

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1607
           1       0.74      0.47      0.57       393

    accuracy                           0.86      2000
   macro avg       0.81      0.71      0.75      2000
weighted avg       0.85      0.86      0.85      2000

In [18]:
def on_premise_deployment():
    start = time.time()
    model.predict(X_test)
    end = time.time()
    return end - start

In [20]:
def cloud_deployment():

    network_delay = 0.25
    start = time.time()
    time.sleep(network_delay)
    model.predict(X_test)
    end = time.time()
    return end - start

In [22]:
def edge_deployment():

    edge_data = X_test[:40]
    start = time.time()
    model.predict(edge_data)
    end = time.time()
    return end - start

In [23]:
on_prem_time = on_premise_deployment()
cloud_time = cloud_deployment()
edge_time = edge_deployment()

In [24]:
print("\nDeployment Latency Comparison")
print("--------------------------------")
print("On-Premise Latency :", round(on_prem_time,4),"seconds")
print("Cloud Latency      :", round(cloud_time,4),"seconds")
print("Edge Latency       :", round(edge_time,4),"seconds")

Deployment Latency Comparison
--------------------------------
On-Premise Latency : 0.0512 seconds
Cloud Latency      : 0.2993 seconds
Edge Latency       : 0.0105 seconds

In [25]:
print("\nDeployment Trade-Off Analysis")

print("\nCloud:")
print("High scalability, but higher latency due to network and pay-as-you-go cost.")

print("\nOn-Premise:")
print("Low latency with strong security but requires expensive infrastructure.")

print("\nEdge Computing:")
print("Very low latency suitable for real-time applications but limited computing power.")

Deployment Trade-Off Analysis

Cloud:
High scalability, but higher latency due to network and pay-as-you-go cost.

On-Premise:
Low latency with strong security but requires expensive infrastructure.

Edge Computing:
Very low latency suitable for real-time applications but limited computing power.